<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260802135719 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE stock_vetement (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              type VARCHAR(20) NOT NULL,
              taille VARCHAR(10) NOT NULL,
              quantite INT NOT NULL,
              marque VARCHAR(100) DEFAULT NULL,
              commentaire TEXT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE stock_volant (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              type VARCHAR(20) NOT NULL,
              vitesse VARCHAR(5) NOT NULL,
              destination VARCHAR(20) NOT NULL,
              quantite_tubes INT NOT NULL,
              marque VARCHAR(100) DEFAULT NULL,
              commentaire TEXT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE stock_vetement');
        $this->addSql('DROP TABLE stock_volant');
    }
}
