<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260802120137 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE creneau (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              nom VARCHAR(100) NOT NULL,
              jour_semaine VARCHAR(10) NOT NULL,
              heure_debut TIME(0) WITHOUT TIME ZONE NOT NULL,
              heure_fin TIME(0) WITHOUT TIME ZONE NOT NULL,
              encadre BOOLEAN NOT NULL,
              gymnase_id INT NOT NULL,
              entraineur_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_F9668B5FF4F4DDD0 ON creneau (gymnase_id)');
        $this->addSql('CREATE INDEX IDX_F9668B5FF8478A1 ON creneau (entraineur_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE gymnase (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              nom VARCHAR(150) NOT NULL,
              adresse VARCHAR(255) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE "licencie" (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              email VARCHAR(180) NOT NULL,
              roles JSON NOT NULL,
              password VARCHAR(255) NOT NULL,
              prenom VARCHAR(100) NOT NULL,
              nom VARCHAR(100) NOT NULL,
              telephone VARCHAR(30) DEFAULT NULL,
              date_naissance TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              numero_licence VARCHAR(20) DEFAULT NULL,
              classement_simple INT DEFAULT NULL,
              classement_double INT DEFAULT NULL,
              classement_mixte INT DEFAULT NULL,
              classement_mis_ajour_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3B755612E7927C74 ON "licencie" (email)');
        $this->addSql(<<<'SQL'
            CREATE TABLE presence (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              present BOOLEAN NOT NULL,
              repondule TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              creneau_id INT NOT NULL,
              licencie_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_6977C7A57D0729A9 ON presence (creneau_id)');
        $this->addSql('CREATE INDEX IDX_6977C7A5B56DCD74 ON presence (licencie_id)');
        $this->addSql('CREATE UNIQUE INDEX presence_unique ON presence (creneau_id, licencie_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              creneau
            ADD
              CONSTRAINT FK_F9668B5FF4F4DDD0 FOREIGN KEY (gymnase_id) REFERENCES gymnase (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              creneau
            ADD
              CONSTRAINT FK_F9668B5FF8478A1 FOREIGN KEY (entraineur_id) REFERENCES "licencie" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              presence
            ADD
              CONSTRAINT FK_6977C7A57D0729A9 FOREIGN KEY (creneau_id) REFERENCES creneau (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              presence
            ADD
              CONSTRAINT FK_6977C7A5B56DCD74 FOREIGN KEY (licencie_id) REFERENCES "licencie" (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE creneau DROP CONSTRAINT FK_F9668B5FF4F4DDD0');
        $this->addSql('ALTER TABLE creneau DROP CONSTRAINT FK_F9668B5FF8478A1');
        $this->addSql('ALTER TABLE presence DROP CONSTRAINT FK_6977C7A57D0729A9');
        $this->addSql('ALTER TABLE presence DROP CONSTRAINT FK_6977C7A5B56DCD74');
        $this->addSql('DROP TABLE creneau');
        $this->addSql('DROP TABLE gymnase');
        $this->addSql('DROP TABLE "licencie"');
        $this->addSql('DROP TABLE presence');
    }
}
