<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260802205839 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE demande_cordage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tension VARCHAR(20) DEFAULT NULL, lieu_depose VARCHAR(150) NOT NULL, lieu_retour VARCHAR(150) DEFAULT NULL, prix VARCHAR(255) DEFAULT NULL, statut VARCHAR(20) NOT NULL, date_depot TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_prete TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_recuperee TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, licencie_id INT NOT NULL, type_cordage_id INT DEFAULT NULL, cordeur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8740957DB56DCD74 ON demande_cordage (licencie_id)');
        $this->addSql('CREATE INDEX IDX_8740957DAB4DDDFF ON demande_cordage (type_cordage_id)');
        $this->addSql('CREATE INDEX IDX_8740957DFA31E208 ON demande_cordage (cordeur_id)');
        $this->addSql('CREATE TABLE type_cordage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE demande_cordage ADD CONSTRAINT FK_8740957DB56DCD74 FOREIGN KEY (licencie_id) REFERENCES "licencie" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demande_cordage ADD CONSTRAINT FK_8740957DAB4DDDFF FOREIGN KEY (type_cordage_id) REFERENCES type_cordage (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demande_cordage ADD CONSTRAINT FK_8740957DFA31E208 FOREIGN KEY (cordeur_id) REFERENCES "licencie" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE demande_cordage DROP CONSTRAINT FK_8740957DB56DCD74');
        $this->addSql('ALTER TABLE demande_cordage DROP CONSTRAINT FK_8740957DAB4DDDFF');
        $this->addSql('ALTER TABLE demande_cordage DROP CONSTRAINT FK_8740957DFA31E208');
        $this->addSql('DROP TABLE demande_cordage');
        $this->addSql('DROP TABLE type_cordage');
    }
}
