<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260802204856 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE equipe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, categorie VARCHAR(50) DEFAULT NULL, capitaine_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2449BA152A10D79E ON equipe (capitaine_id)');
        $this->addSql('CREATE TABLE equipe_membre (equipe_id INT NOT NULL, licencie_id INT NOT NULL, PRIMARY KEY (equipe_id, licencie_id))');
        $this->addSql('CREATE INDEX IDX_FB839D816D861B89 ON equipe_membre (equipe_id)');
        $this->addSql('CREATE INDEX IDX_FB839D81B56DCD74 ON equipe_membre (licencie_id)');
        $this->addSql('ALTER TABLE equipe ADD CONSTRAINT FK_2449BA152A10D79E FOREIGN KEY (capitaine_id) REFERENCES "licencie" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE equipe_membre ADD CONSTRAINT FK_FB839D816D861B89 FOREIGN KEY (equipe_id) REFERENCES equipe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE equipe_membre ADD CONSTRAINT FK_FB839D81B56DCD74 FOREIGN KEY (licencie_id) REFERENCES "licencie" (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE equipe DROP CONSTRAINT FK_2449BA152A10D79E');
        $this->addSql('ALTER TABLE equipe_membre DROP CONSTRAINT FK_FB839D816D861B89');
        $this->addSql('ALTER TABLE equipe_membre DROP CONSTRAINT FK_FB839D81B56DCD74');
        $this->addSql('DROP TABLE equipe');
        $this->addSql('DROP TABLE equipe_membre');
    }
}
