<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260804172724 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE inventaire_campagne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, statut VARCHAR(20) NOT NULL, cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, validee_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, auteur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_217B21E960BB6FE6 ON inventaire_campagne (auteur_id)');
        $this->addSql('CREATE TABLE inventaire_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle_article VARCHAR(255) NOT NULL, quantite_theorique INT NOT NULL, quantite_comptee INT DEFAULT NULL, motif VARCHAR(255) DEFAULT NULL, campagne_id INT NOT NULL, vetement_id INT DEFAULT NULL, volant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BC31A1E116227374 ON inventaire_ligne (campagne_id)');
        $this->addSql('CREATE INDEX IDX_BC31A1E1969D8B67 ON inventaire_ligne (vetement_id)');
        $this->addSql('CREATE INDEX IDX_BC31A1E1B89A044D ON inventaire_ligne (volant_id)');
        $this->addSql('ALTER TABLE inventaire_campagne ADD CONSTRAINT FK_217B21E960BB6FE6 FOREIGN KEY (auteur_id) REFERENCES "licencie" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventaire_ligne ADD CONSTRAINT FK_BC31A1E116227374 FOREIGN KEY (campagne_id) REFERENCES inventaire_campagne (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventaire_ligne ADD CONSTRAINT FK_BC31A1E1969D8B67 FOREIGN KEY (vetement_id) REFERENCES stock_vetement (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventaire_ligne ADD CONSTRAINT FK_BC31A1E1B89A044D FOREIGN KEY (volant_id) REFERENCES stock_volant (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_vetement ADD seuil_alerte INT DEFAULT NULL');
        $this->addSql('ALTER TABLE stock_volant ADD seuil_alerte INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE inventaire_campagne DROP CONSTRAINT FK_217B21E960BB6FE6');
        $this->addSql('ALTER TABLE inventaire_ligne DROP CONSTRAINT FK_BC31A1E116227374');
        $this->addSql('ALTER TABLE inventaire_ligne DROP CONSTRAINT FK_BC31A1E1969D8B67');
        $this->addSql('ALTER TABLE inventaire_ligne DROP CONSTRAINT FK_BC31A1E1B89A044D');
        $this->addSql('DROP TABLE inventaire_campagne');
        $this->addSql('DROP TABLE inventaire_ligne');
        $this->addSql('ALTER TABLE stock_vetement DROP seuil_alerte');
        $this->addSql('ALTER TABLE stock_volant DROP seuil_alerte');
    }
}
