<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260816140333 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute la table seance_schema (tableau blanc terrain de badminton, plusieurs schémas par séance).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE seance_schema (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(100) DEFAULT NULL, donnees TEXT NOT NULL, ordre INT NOT NULL, modifie_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, seance_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C7FB5AFAE3797A94 ON seance_schema (seance_id)');
        $this->addSql('ALTER TABLE seance_schema ADD CONSTRAINT FK_C7FB5AFAE3797A94 FOREIGN KEY (seance_id) REFERENCES seance (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE seance_schema DROP CONSTRAINT FK_C7FB5AFAE3797A94');
        $this->addSql('DROP TABLE seance_schema');
    }
}
