<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260816130921 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la table lien_familial (liens familiaux élargis entre licenciés, avec consentement).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE lien_familial (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_lien VARCHAR(40) NOT NULL, statut VARCHAR(20) NOT NULL, demande_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accepte_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, demandeur_id INT NOT NULL, cible_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7899DBF495A6EE59 ON lien_familial (demandeur_id)');
        $this->addSql('CREATE INDEX IDX_7899DBF4A96E5E09 ON lien_familial (cible_id)');
        $this->addSql('ALTER TABLE lien_familial ADD CONSTRAINT FK_7899DBF495A6EE59 FOREIGN KEY (demandeur_id) REFERENCES licencie (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lien_familial ADD CONSTRAINT FK_7899DBF4A96E5E09 FOREIGN KEY (cible_id) REFERENCES licencie (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE lien_familial DROP CONSTRAINT FK_7899DBF495A6EE59');
        $this->addSql('ALTER TABLE lien_familial DROP CONSTRAINT FK_7899DBF4A96E5E09');
        $this->addSql('DROP TABLE lien_familial');
    }
}
