<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260802142838 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE adhesion (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              payee BOOLEAN NOT NULL,
              date_paiement TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              licencie_id INT NOT NULL,
              saison_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_C50CA65AB56DCD74 ON adhesion (licencie_id)');
        $this->addSql('CREATE INDEX IDX_C50CA65AF965414C ON adhesion (saison_id)');
        $this->addSql('CREATE UNIQUE INDEX adhesion_unique ON adhesion (licencie_id, saison_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE saison (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              libelle VARCHAR(20) NOT NULL,
              date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              date_fin TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              adhesion
            ADD
              CONSTRAINT FK_C50CA65AB56DCD74 FOREIGN KEY (licencie_id) REFERENCES "licencie" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              adhesion
            ADD
              CONSTRAINT FK_C50CA65AF965414C FOREIGN KEY (saison_id) REFERENCES saison (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE adhesion DROP CONSTRAINT FK_C50CA65AB56DCD74');
        $this->addSql('ALTER TABLE adhesion DROP CONSTRAINT FK_C50CA65AF965414C');
        $this->addSql('DROP TABLE adhesion');
        $this->addSql('DROP TABLE saison');
    }
}
