<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260804195939 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE journal_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, utilisateur_libelle VARCHAR(150) DEFAULT NULL, action VARCHAR(60) NOT NULL, objet_type VARCHAR(100) DEFAULT NULL, objet_libelle VARCHAR(150) DEFAULT NULL, ancienne_valeur TEXT DEFAULT NULL, nouvelle_valeur TEXT DEFAULT NULL, horodatage TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_71C3CC53FB88E14F ON journal_audit (utilisateur_id)');
        $this->addSql('ALTER TABLE journal_audit ADD CONSTRAINT FK_71C3CC53FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES "licencie" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE journal_audit DROP CONSTRAINT FK_71C3CC53FB88E14F');
        $this->addSql('DROP TABLE journal_audit');
    }
}
