<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260804165648 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE communication_envoi (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sujet VARCHAR(255) NOT NULL, corps TEXT NOT NULL, cible_libelle VARCHAR(255) NOT NULL, nombre_destinataires INT NOT NULL, nombre_echecs INT NOT NULL, emails_en_echec TEXT DEFAULT NULL, envoye_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, auteur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4BFFF4D360BB6FE6 ON communication_envoi (auteur_id)');
        $this->addSql('ALTER TABLE communication_envoi ADD CONSTRAINT FK_4BFFF4D360BB6FE6 FOREIGN KEY (auteur_id) REFERENCES "licencie" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE communication_envoi DROP CONSTRAINT FK_4BFFF4D360BB6FE6');
        $this->addSql('DROP TABLE communication_envoi');
    }
}
