<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260804170627 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE match_interclub (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(5) NOT NULL, adversaires VARCHAR(200) DEFAULT NULL, score VARCHAR(100) DEFAULT NULL, gagne BOOLEAN DEFAULT NULL, rencontre_id INT NOT NULL, joueur1_id INT DEFAULT NULL, joueur2_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_90BFE3636CFC0818 ON match_interclub (rencontre_id)');
        $this->addSql('CREATE INDEX IDX_90BFE36392C1E237 ON match_interclub (joueur1_id)');
        $this->addSql('CREATE INDEX IDX_90BFE36380744DD9 ON match_interclub (joueur2_id)');
        $this->addSql('ALTER TABLE match_interclub ADD CONSTRAINT FK_90BFE3636CFC0818 FOREIGN KEY (rencontre_id) REFERENCES rencontre_interclub (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE match_interclub ADD CONSTRAINT FK_90BFE36392C1E237 FOREIGN KEY (joueur1_id) REFERENCES "licencie" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE match_interclub ADD CONSTRAINT FK_90BFE36380744DD9 FOREIGN KEY (joueur2_id) REFERENCES "licencie" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE equipe ADD championnat VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE equipe ADD division VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE rencontre_interclub ADD domicile BOOLEAN NOT NULL DEFAULT true');
        $this->addSql('ALTER TABLE rencontre_interclub ALTER COLUMN domicile DROP DEFAULT');
        $this->addSql('ALTER TABLE rencontre_interclub ADD heure_rdv TIME(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE rencontre_interclub ADD covoiturage TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE rencontre_interclub ADD capitaine_rencontre_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE rencontre_interclub ADD CONSTRAINT FK_125C58851927D671 FOREIGN KEY (capitaine_rencontre_id) REFERENCES "licencie" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_125C58851927D671 ON rencontre_interclub (capitaine_rencontre_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE match_interclub DROP CONSTRAINT FK_90BFE3636CFC0818');
        $this->addSql('ALTER TABLE match_interclub DROP CONSTRAINT FK_90BFE36392C1E237');
        $this->addSql('ALTER TABLE match_interclub DROP CONSTRAINT FK_90BFE36380744DD9');
        $this->addSql('DROP TABLE match_interclub');
        $this->addSql('ALTER TABLE equipe DROP championnat');
        $this->addSql('ALTER TABLE equipe DROP division');
        $this->addSql('ALTER TABLE rencontre_interclub DROP CONSTRAINT FK_125C58851927D671');
        $this->addSql('DROP INDEX IDX_125C58851927D671');
        $this->addSql('ALTER TABLE rencontre_interclub DROP domicile');
        $this->addSql('ALTER TABLE rencontre_interclub DROP heure_rdv');
        $this->addSql('ALTER TABLE rencontre_interclub DROP covoiturage');
        $this->addSql('ALTER TABLE rencontre_interclub DROP capitaine_rencontre_id');
    }
}
