<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260816195248 extends AbstractMigration
{
    public function getDescription(): string
    {
        return "Ajoute les documents d'événement, le module salariés (RH), et le champ double licence sur le licencié.";
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE evenement_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_original VARCHAR(255) NOT NULL, chemin VARCHAR(500) NOT NULL, ajoute_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, evenement_id INT NOT NULL, ajoute_par_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_570F119EFD02F13 ON evenement_document (evenement_id)');
        $this->addSql('CREATE INDEX IDX_570F119EDAA76F43 ON evenement_document (ajoute_par_id)');
        $this->addSql('CREATE TABLE salarie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prenom VARCHAR(100) NOT NULL, nom VARCHAR(100) NOT NULL, poste VARCHAR(150) NOT NULL, type_contrat VARCHAR(20) NOT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, telephone VARCHAR(30) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, notes TEXT DEFAULT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE evenement_document ADD CONSTRAINT FK_570F119EFD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE evenement_document ADD CONSTRAINT FK_570F119EDAA76F43 FOREIGN KEY (ajoute_par_id) REFERENCES licencie (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE licencie ADD double_licence BOOLEAN NOT NULL DEFAULT false');
        $this->addSql('ALTER TABLE licencie ALTER COLUMN double_licence DROP DEFAULT');
        $this->addSql('ALTER TABLE licencie ADD club_double_licence VARCHAR(150) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE evenement_document DROP CONSTRAINT FK_570F119EFD02F13');
        $this->addSql('ALTER TABLE evenement_document DROP CONSTRAINT FK_570F119EDAA76F43');
        $this->addSql('DROP TABLE evenement_document');
        $this->addSql('DROP TABLE salarie');
        $this->addSql('ALTER TABLE licencie DROP double_licence');
        $this->addSql('ALTER TABLE licencie DROP club_double_licence');
    }
}
