<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260804205051 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE push_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, endpoint TEXT NOT NULL, p256dh_key VARCHAR(255) NOT NULL, auth_token VARCHAR(255) NOT NULL, cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, licencie_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_562830F3C4420F7B ON push_subscription (endpoint)');
        $this->addSql('CREATE INDEX IDX_562830F3B56DCD74 ON push_subscription (licencie_id)');
        $this->addSql('ALTER TABLE push_subscription ADD CONSTRAINT FK_562830F3B56DCD74 FOREIGN KEY (licencie_id) REFERENCES "licencie" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE push_subscription DROP CONSTRAINT FK_562830F3B56DCD74');
        $this->addSql('DROP TABLE push_subscription');
    }
}
