<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260802140349 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE creneau_ouverture (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              creneau_id INT NOT NULL,
              licencie_ouverture_id INT DEFAULT NULL,
              licencie_fermeture_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_45A72AD77D0729A9 ON creneau_ouverture (creneau_id)');
        $this->addSql('CREATE INDEX IDX_45A72AD7BAB2A522 ON creneau_ouverture (licencie_ouverture_id)');
        $this->addSql('CREATE INDEX IDX_45A72AD74DA06128 ON creneau_ouverture (licencie_fermeture_id)');
        $this->addSql('CREATE UNIQUE INDEX creneau_ouverture_unique ON creneau_ouverture (creneau_id, date)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              creneau_ouverture
            ADD
              CONSTRAINT FK_45A72AD77D0729A9 FOREIGN KEY (creneau_id) REFERENCES creneau (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              creneau_ouverture
            ADD
              CONSTRAINT FK_45A72AD7BAB2A522 FOREIGN KEY (licencie_ouverture_id) REFERENCES "licencie" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              creneau_ouverture
            ADD
              CONSTRAINT FK_45A72AD74DA06128 FOREIGN KEY (licencie_fermeture_id) REFERENCES "licencie" (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE creneau_ouverture DROP CONSTRAINT FK_45A72AD77D0729A9');
        $this->addSql('ALTER TABLE creneau_ouverture DROP CONSTRAINT FK_45A72AD7BAB2A522');
        $this->addSql('ALTER TABLE creneau_ouverture DROP CONSTRAINT FK_45A72AD74DA06128');
        $this->addSql('DROP TABLE creneau_ouverture');
    }
}
