<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260805144209 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE modele_communication (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              nom VARCHAR(150) NOT NULL,
              sujet VARCHAR(255) NOT NULL,
              corps TEXT NOT NULL,
              cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql("ALTER TABLE communication_envoi ADD statut VARCHAR(20) NOT NULL DEFAULT 'ENVOYE'");
        $this->addSql('ALTER TABLE communication_envoi ALTER COLUMN statut DROP DEFAULT');
        $this->addSql('ALTER TABLE communication_envoi ADD planifie_pour TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE communication_envoi ADD destinataires_ids TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE communication_envoi ADD piece_jointe_nom VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE communication_envoi ADD piece_jointe_chemin VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE modele_communication');
        $this->addSql('ALTER TABLE communication_envoi DROP statut');
        $this->addSql('ALTER TABLE communication_envoi DROP planifie_pour');
        $this->addSql('ALTER TABLE communication_envoi DROP destinataires_ids');
        $this->addSql('ALTER TABLE communication_envoi DROP piece_jointe_nom');
        $this->addSql('ALTER TABLE communication_envoi DROP piece_jointe_chemin');
    }
}
