<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260804164619 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE creneau_exception (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(20) NOT NULL, heure_debut TIME(0) WITHOUT TIME ZONE DEFAULT NULL, heure_fin TIME(0) WITHOUT TIME ZONE DEFAULT NULL, capacite_max INT DEFAULT NULL, note TEXT DEFAULT NULL, creneau_id INT NOT NULL, gymnase_id INT DEFAULT NULL, entraineur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7928BA117D0729A9 ON creneau_exception (creneau_id)');
        $this->addSql('CREATE INDEX IDX_7928BA11F4F4DDD0 ON creneau_exception (gymnase_id)');
        $this->addSql('CREATE INDEX IDX_7928BA11F8478A1 ON creneau_exception (entraineur_id)');
        $this->addSql('CREATE UNIQUE INDEX creneau_exception_unique ON creneau_exception (creneau_id, date)');
        $this->addSql('ALTER TABLE creneau_exception ADD CONSTRAINT FK_7928BA117D0729A9 FOREIGN KEY (creneau_id) REFERENCES creneau (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE creneau_exception ADD CONSTRAINT FK_7928BA11F4F4DDD0 FOREIGN KEY (gymnase_id) REFERENCES gymnase (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE creneau_exception ADD CONSTRAINT FK_7928BA11F8478A1 FOREIGN KEY (entraineur_id) REFERENCES "licencie" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE creneau_exception DROP CONSTRAINT FK_7928BA117D0729A9');
        $this->addSql('ALTER TABLE creneau_exception DROP CONSTRAINT FK_7928BA11F4F4DDD0');
        $this->addSql('ALTER TABLE creneau_exception DROP CONSTRAINT FK_7928BA11F8478A1');
        $this->addSql('DROP TABLE creneau_exception');
    }
}
