<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260817055852 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la messagerie privée entre licenciés (conversation + message).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, dernier_message_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, vu_par_participant1_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, vu_par_participant2_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, participant1_id INT NOT NULL, participant2_id INT NOT NULL, dernier_message_expediteur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A8E26E9B29A9963 ON conversation (participant1_id)');
        $this->addSql('CREATE INDEX IDX_8A8E26E9A02F368D ON conversation (participant2_id)');
        $this->addSql('CREATE INDEX IDX_8A8E26E9E2CFEB67 ON conversation (dernier_message_expediteur_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, envoye_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, conversation_id INT NOT NULL, expediteur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F9AC0396 ON message (conversation_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307F10335F61 ON message (expediteur_id)');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9B29A9963 FOREIGN KEY (participant1_id) REFERENCES "licencie" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9A02F368D FOREIGN KEY (participant2_id) REFERENCES "licencie" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9E2CFEB67 FOREIGN KEY (dernier_message_expediteur_id) REFERENCES "licencie" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F10335F61 FOREIGN KEY (expediteur_id) REFERENCES "licencie" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E9B29A9963');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E9A02F368D');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E9E2CFEB67');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F9AC0396');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F10335F61');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE message');
    }
}
