<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260802211553 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE convocation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, present BOOLEAN DEFAULT NULL, repondule TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, rencontre_id INT NOT NULL, licencie_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C03B3F5F6CFC0818 ON convocation (rencontre_id)');
        $this->addSql('CREATE INDEX IDX_C03B3F5FB56DCD74 ON convocation (licencie_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C03B3F5F6CFC0818B56DCD74 ON convocation (rencontre_id, licencie_id)');
        $this->addSql('CREATE TABLE rencontre_interclub (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, journee INT NOT NULL, date_rencontre TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lieu VARCHAR(150) NOT NULL, adversaire VARCHAR(150) NOT NULL, score_equipe INT DEFAULT NULL, score_adversaire INT DEFAULT NULL, equipe_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_125C58856D861B89 ON rencontre_interclub (equipe_id)');
        $this->addSql('ALTER TABLE convocation ADD CONSTRAINT FK_C03B3F5F6CFC0818 FOREIGN KEY (rencontre_id) REFERENCES rencontre_interclub (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE convocation ADD CONSTRAINT FK_C03B3F5FB56DCD74 FOREIGN KEY (licencie_id) REFERENCES "licencie" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rencontre_interclub ADD CONSTRAINT FK_125C58856D861B89 FOREIGN KEY (equipe_id) REFERENCES equipe (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE convocation DROP CONSTRAINT FK_C03B3F5F6CFC0818');
        $this->addSql('ALTER TABLE convocation DROP CONSTRAINT FK_C03B3F5FB56DCD74');
        $this->addSql('ALTER TABLE rencontre_interclub DROP CONSTRAINT FK_125C58856D861B89');
        $this->addSql('DROP TABLE convocation');
        $this->addSql('DROP TABLE rencontre_interclub');
    }
}
