<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260817060658 extends AbstractMigration
{
    public function getDescription(): string
    {
        return "Conversation à deux (participant1/participant2) -> table de liaison conversation_participant (1 à N participants), pour permettre les discussions de groupe. Ajoute titre et créateur.";
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE conversation_participant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vu_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, conversation_id INT NOT NULL, licencie_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_398016619AC0396 ON conversation_participant (conversation_id)');
        $this->addSql('CREATE INDEX IDX_39801661B56DCD74 ON conversation_participant (licencie_id)');
        $this->addSql('CREATE UNIQUE INDEX conversation_participant_unique ON conversation_participant (conversation_id, licencie_id)');
        $this->addSql('ALTER TABLE conversation_participant ADD CONSTRAINT FK_398016619AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation_participant ADD CONSTRAINT FK_39801661B56DCD74 FOREIGN KEY (licencie_id) REFERENCES licencie (id) ON DELETE CASCADE NOT DEFERRABLE');

        // Migration des données : chaque conversation à deux devient deux lignes dans la table de
        // liaison, avant de supprimer les anciennes colonnes.
        $this->addSql('INSERT INTO conversation_participant (conversation_id, licencie_id, vu_le) SELECT id, participant1_id, vu_par_participant1_le FROM conversation');
        $this->addSql('INSERT INTO conversation_participant (conversation_id, licencie_id, vu_le) SELECT id, participant2_id, vu_par_participant2_le FROM conversation');

        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT fk_8a8e26e9a02f368d');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT fk_8a8e26e9b29a9963');
        $this->addSql('DROP INDEX idx_8a8e26e9a02f368d');
        $this->addSql('DROP INDEX idx_8a8e26e9b29a9963');
        $this->addSql('ALTER TABLE conversation ADD titre VARCHAR(150) DEFAULT NULL');
        $this->addSql('ALTER TABLE conversation ADD createur_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE conversation DROP vu_par_participant1_le');
        $this->addSql('ALTER TABLE conversation DROP vu_par_participant2_le');
        $this->addSql('ALTER TABLE conversation DROP participant1_id');
        $this->addSql('ALTER TABLE conversation DROP participant2_id');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E973A201E5 FOREIGN KEY (createur_id) REFERENCES licencie (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_8A8E26E973A201E5 ON conversation (createur_id)');
    }

    public function down(Schema $schema): void
    {
        // Restauration structurelle uniquement — ne réattribue pas les participants au-delà de 2
        // pour une éventuelle conversation de groupe créée entre-temps (perte de données possible
        // sur ce cas précis, acceptable pour un rollback).
        $this->addSql('ALTER TABLE conversation_participant DROP CONSTRAINT FK_398016619AC0396');
        $this->addSql('ALTER TABLE conversation_participant DROP CONSTRAINT FK_39801661B56DCD74');
        $this->addSql('DROP TABLE conversation_participant');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E973A201E5');
        $this->addSql('DROP INDEX IDX_8A8E26E973A201E5');
        $this->addSql('ALTER TABLE conversation ADD vu_par_participant1_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE conversation ADD vu_par_participant2_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE conversation ADD participant1_id INT NOT NULL');
        $this->addSql('ALTER TABLE conversation ADD participant2_id INT NOT NULL');
        $this->addSql('ALTER TABLE conversation DROP titre');
        $this->addSql('ALTER TABLE conversation DROP createur_id');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT fk_8a8e26e9a02f368d FOREIGN KEY (participant2_id) REFERENCES licencie (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT fk_8a8e26e9b29a9963 FOREIGN KEY (participant1_id) REFERENCES licencie (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_8a8e26e9a02f368d ON conversation (participant2_id)');
        $this->addSql('CREATE INDEX idx_8a8e26e9b29a9963 ON conversation (participant1_id)');
    }
}
