<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260802203039 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE paiement_adhesion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, montant NUMERIC(8, 2) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, moyen VARCHAR(20) NOT NULL, numero_cheque VARCHAR(30) DEFAULT NULL, adhesion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FAB5E60F68139D7 ON paiement_adhesion (adhesion_id)');
        $this->addSql('ALTER TABLE paiement_adhesion ADD CONSTRAINT FK_FAB5E60F68139D7 FOREIGN KEY (adhesion_id) REFERENCES adhesion (id) NOT DEFERRABLE');
        $this->addSql("ALTER TABLE adhesion ADD statut VARCHAR(15) NOT NULL DEFAULT 'EN_ATTENTE'");
        $this->addSql("UPDATE adhesion SET statut = 'PAYEE' WHERE payee = true");
        $this->addSql('ALTER TABLE adhesion ALTER statut DROP DEFAULT');
        $this->addSql('ALTER TABLE adhesion ADD montant_total NUMERIC(8, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE adhesion DROP payee');
        $this->addSql('ALTER TABLE adhesion DROP date_paiement');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE paiement_adhesion DROP CONSTRAINT FK_FAB5E60F68139D7');
        $this->addSql('DROP TABLE paiement_adhesion');
        $this->addSql('ALTER TABLE adhesion ADD payee BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE adhesion ADD date_paiement TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE adhesion DROP statut');
        $this->addSql('ALTER TABLE adhesion DROP montant_total');
    }
}
