<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260805143400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE notification_envoyee (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              destinataire_libelle VARCHAR(150) DEFAULT NULL,
              sujet VARCHAR(255) NOT NULL,
              extrait VARCHAR(200) DEFAULT NULL,
              email_envoye BOOLEAN NOT NULL,
              push_envoye BOOLEAN NOT NULL,
              envoye_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              destinataire_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_8A7F371A4F84F6E ON notification_envoyee (destinataire_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              notification_envoyee
            ADD
              CONSTRAINT FK_8A7F371A4F84F6E FOREIGN KEY (destinataire_id) REFERENCES "licencie" (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE notification_envoyee DROP CONSTRAINT FK_8A7F371A4F84F6E');
        $this->addSql('DROP TABLE notification_envoyee');
    }
}
