<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260816132520 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Créneau : entraîneur unique -> plusieurs entraîneurs (table creneau_entraineur, données migrées). Ajoute la table seance (contenu des séances dirigées).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE creneau_entraineur (creneau_id INT NOT NULL, licencie_id INT NOT NULL, PRIMARY KEY (creneau_id, licencie_id))');
        $this->addSql('CREATE INDEX IDX_6491A2A47D0729A9 ON creneau_entraineur (creneau_id)');
        $this->addSql('CREATE INDEX IDX_6491A2A4B56DCD74 ON creneau_entraineur (licencie_id)');
        $this->addSql('CREATE TABLE seance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, objectifs TEXT DEFAULT NULL, contenu TEXT DEFAULT NULL, publiee BOOLEAN NOT NULL, cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modifie_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, creneau_id INT NOT NULL, redacteur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DF7DFD0E7D0729A9 ON seance (creneau_id)');
        $this->addSql('CREATE INDEX IDX_DF7DFD0E764D0490 ON seance (redacteur_id)');
        $this->addSql('CREATE UNIQUE INDEX seance_unique ON seance (creneau_id, date)');
        $this->addSql('ALTER TABLE creneau_entraineur ADD CONSTRAINT FK_6491A2A47D0729A9 FOREIGN KEY (creneau_id) REFERENCES creneau (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE creneau_entraineur ADD CONSTRAINT FK_6491A2A4B56DCD74 FOREIGN KEY (licencie_id) REFERENCES licencie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE seance ADD CONSTRAINT FK_DF7DFD0E7D0729A9 FOREIGN KEY (creneau_id) REFERENCES creneau (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE seance ADD CONSTRAINT FK_DF7DFD0E764D0490 FOREIGN KEY (redacteur_id) REFERENCES licencie (id) ON DELETE SET NULL NOT DEFERRABLE');

        // Migration des données : chaque créneau ayant un entraineur_id devient une ligne dans la
        // nouvelle table de liaison, avant de supprimer la colonne.
        $this->addSql('INSERT INTO creneau_entraineur (creneau_id, licencie_id) SELECT id, entraineur_id FROM creneau WHERE entraineur_id IS NOT NULL');

        $this->addSql('ALTER TABLE creneau DROP CONSTRAINT fk_f9668b5ff8478a1');
        $this->addSql('DROP INDEX idx_f9668b5ff8478a1');
        $this->addSql('ALTER TABLE creneau DROP entraineur_id');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE creneau ADD entraineur_id INT DEFAULT NULL');

        // Restaure un seul entraîneur par créneau (le premier de la liste) — perte d'information
        // si plusieurs entraîneurs avaient été ajoutés depuis.
        $this->addSql('UPDATE creneau SET entraineur_id = (SELECT MIN(licencie_id) FROM creneau_entraineur WHERE creneau_entraineur.creneau_id = creneau.id)');

        $this->addSql('ALTER TABLE creneau ADD CONSTRAINT fk_f9668b5ff8478a1 FOREIGN KEY (entraineur_id) REFERENCES licencie (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_f9668b5ff8478a1 ON creneau (entraineur_id)');

        $this->addSql('ALTER TABLE creneau_entraineur DROP CONSTRAINT FK_6491A2A47D0729A9');
        $this->addSql('ALTER TABLE creneau_entraineur DROP CONSTRAINT FK_6491A2A4B56DCD74');
        $this->addSql('ALTER TABLE seance DROP CONSTRAINT FK_DF7DFD0E7D0729A9');
        $this->addSql('ALTER TABLE seance DROP CONSTRAINT FK_DF7DFD0E764D0490');
        $this->addSql('DROP TABLE creneau_entraineur');
        $this->addSql('DROP TABLE seance');
    }
}
