<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260802141757 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE stock_mouvement_vetement (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              type VARCHAR(10) NOT NULL,
              quantite INT NOT NULL,
              motif VARCHAR(255) DEFAULT NULL,
              cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              article_id INT NOT NULL,
              auteur_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_4D38F1A7294869C ON stock_mouvement_vetement (article_id)');
        $this->addSql('CREATE INDEX IDX_4D38F1A60BB6FE6 ON stock_mouvement_vetement (auteur_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE stock_mouvement_volant (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              type VARCHAR(10) NOT NULL,
              quantite INT NOT NULL,
              motif VARCHAR(255) DEFAULT NULL,
              cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              article_id INT NOT NULL,
              auteur_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_385801707294869C ON stock_mouvement_volant (article_id)');
        $this->addSql('CREATE INDEX IDX_3858017060BB6FE6 ON stock_mouvement_volant (auteur_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              stock_mouvement_vetement
            ADD
              CONSTRAINT FK_4D38F1A7294869C FOREIGN KEY (article_id) REFERENCES stock_vetement (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              stock_mouvement_vetement
            ADD
              CONSTRAINT FK_4D38F1A60BB6FE6 FOREIGN KEY (auteur_id) REFERENCES "licencie" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              stock_mouvement_volant
            ADD
              CONSTRAINT FK_385801707294869C FOREIGN KEY (article_id) REFERENCES stock_volant (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              stock_mouvement_volant
            ADD
              CONSTRAINT FK_3858017060BB6FE6 FOREIGN KEY (auteur_id) REFERENCES "licencie" (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stock_mouvement_vetement DROP CONSTRAINT FK_4D38F1A7294869C');
        $this->addSql('ALTER TABLE stock_mouvement_vetement DROP CONSTRAINT FK_4D38F1A60BB6FE6');
        $this->addSql('ALTER TABLE stock_mouvement_volant DROP CONSTRAINT FK_385801707294869C');
        $this->addSql('ALTER TABLE stock_mouvement_volant DROP CONSTRAINT FK_3858017060BB6FE6');
        $this->addSql('DROP TABLE stock_mouvement_vetement');
        $this->addSql('DROP TABLE stock_mouvement_volant');
    }
}
