<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260812074217 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stock_cordage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, marque VARCHAR(100) DEFAULT NULL, modele VARCHAR(100) DEFAULT NULL, quantite INT NOT NULL, commentaire TEXT DEFAULT NULL, prix_unitaire VARCHAR(255) DEFAULT NULL, seuil_alerte INT DEFAULT NULL, lieu_stockage VARCHAR(150) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE stock_mouvement_cordage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, quantite INT NOT NULL, motif VARCHAR(255) DEFAULT NULL, cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, article_id INT NOT NULL, auteur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8BC3F707294869C ON stock_mouvement_cordage (article_id)');
        $this->addSql('CREATE INDEX IDX_8BC3F7060BB6FE6 ON stock_mouvement_cordage (auteur_id)');
        $this->addSql('ALTER TABLE stock_mouvement_cordage ADD CONSTRAINT FK_8BC3F707294869C FOREIGN KEY (article_id) REFERENCES stock_cordage (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_mouvement_cordage ADD CONSTRAINT FK_8BC3F7060BB6FE6 FOREIGN KEY (auteur_id) REFERENCES "licencie" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demande_cordage ADD longueur_utilisee_m INT DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_cordage ADD stock_cordage_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_cordage ADD CONSTRAINT FK_8740957D1807FC76 FOREIGN KEY (stock_cordage_id) REFERENCES stock_cordage (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_8740957D1807FC76 ON demande_cordage (stock_cordage_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stock_mouvement_cordage DROP CONSTRAINT FK_8BC3F707294869C');
        $this->addSql('ALTER TABLE stock_mouvement_cordage DROP CONSTRAINT FK_8BC3F7060BB6FE6');
        $this->addSql('DROP TABLE stock_cordage');
        $this->addSql('DROP TABLE stock_mouvement_cordage');
        $this->addSql('ALTER TABLE demande_cordage DROP CONSTRAINT FK_8740957D1807FC76');
        $this->addSql('DROP INDEX IDX_8740957D1807FC76');
        $this->addSql('ALTER TABLE demande_cordage DROP longueur_utilisee_m');
        $this->addSql('ALTER TABLE demande_cordage DROP stock_cordage_id');
    }
}
