<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260802210840 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE evenement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(30) NOT NULL, titre VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, lieu VARCHAR(150) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, nombre_places INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE inscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statut VARCHAR(20) NOT NULL, date_inscription TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, evenement_id INT NOT NULL, licencie_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E90F6D6FD02F13 ON inscription (evenement_id)');
        $this->addSql('CREATE INDEX IDX_5E90F6D6B56DCD74 ON inscription (licencie_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5E90F6D6FD02F13B56DCD74 ON inscription (evenement_id, licencie_id)');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT FK_5E90F6D6FD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT FK_5E90F6D6B56DCD74 FOREIGN KEY (licencie_id) REFERENCES "licencie" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE inscription DROP CONSTRAINT FK_5E90F6D6FD02F13');
        $this->addSql('ALTER TABLE inscription DROP CONSTRAINT FK_5E90F6D6B56DCD74');
        $this->addSql('DROP TABLE evenement');
        $this->addSql('DROP TABLE inscription');
    }
}
