<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260802161152 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cle_gymnase (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(100) DEFAULT NULL, gymnase_id INT NOT NULL, licencie_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5B2083F1F4F4DDD0 ON cle_gymnase (gymnase_id)');
        $this->addSql('CREATE INDEX IDX_5B2083F1B56DCD74 ON cle_gymnase (licencie_id)');
        $this->addSql('ALTER TABLE cle_gymnase ADD CONSTRAINT FK_5B2083F1F4F4DDD0 FOREIGN KEY (gymnase_id) REFERENCES gymnase (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cle_gymnase ADD CONSTRAINT FK_5B2083F1B56DCD74 FOREIGN KEY (licencie_id) REFERENCES "licencie" (id) NOT DEFERRABLE');
        $this->addSql('INSERT INTO cle_gymnase (gymnase_id, licencie_id) SELECT gymnase_id, licencie_id FROM gymnase_porteur_cles');
        $this->addSql('ALTER TABLE gymnase_porteur_cles DROP CONSTRAINT fk_3c8aa230b56dcd74');
        $this->addSql('ALTER TABLE gymnase_porteur_cles DROP CONSTRAINT fk_3c8aa230f4f4ddd0');
        $this->addSql('DROP TABLE gymnase_porteur_cles');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE gymnase_porteur_cles (gymnase_id INT NOT NULL, licencie_id INT NOT NULL, PRIMARY KEY (gymnase_id, licencie_id))');
        $this->addSql('CREATE INDEX idx_3c8aa230b56dcd74 ON gymnase_porteur_cles (licencie_id)');
        $this->addSql('CREATE INDEX idx_3c8aa230f4f4ddd0 ON gymnase_porteur_cles (gymnase_id)');
        $this->addSql('ALTER TABLE gymnase_porteur_cles ADD CONSTRAINT fk_3c8aa230b56dcd74 FOREIGN KEY (licencie_id) REFERENCES licencie (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gymnase_porteur_cles ADD CONSTRAINT fk_3c8aa230f4f4ddd0 FOREIGN KEY (gymnase_id) REFERENCES gymnase (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cle_gymnase DROP CONSTRAINT FK_5B2083F1F4F4DDD0');
        $this->addSql('ALTER TABLE cle_gymnase DROP CONSTRAINT FK_5B2083F1B56DCD74');
        $this->addSql('DROP TABLE cle_gymnase');
    }
}
