<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260804142946 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE raquette (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, marque VARCHAR(100) NOT NULL, modele VARCHAR(100) NOT NULL, signe_distinctif VARCHAR(150) DEFAULT NULL, tension_habituelle VARCHAR(20) DEFAULT NULL, licencie_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7E515196B56DCD74 ON raquette (licencie_id)');
        $this->addSql('ALTER TABLE raquette ADD CONSTRAINT FK_7E515196B56DCD74 FOREIGN KEY (licencie_id) REFERENCES "licencie" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demande_cordage ADD raquette_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_cordage ADD CONSTRAINT FK_8740957D20130C7B FOREIGN KEY (raquette_id) REFERENCES raquette (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_8740957D20130C7B ON demande_cordage (raquette_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE raquette DROP CONSTRAINT FK_7E515196B56DCD74');
        $this->addSql('DROP TABLE raquette');
        $this->addSql('ALTER TABLE demande_cordage DROP CONSTRAINT FK_8740957D20130C7B');
        $this->addSql('DROP INDEX IDX_8740957D20130C7B');
        $this->addSql('ALTER TABLE demande_cordage DROP raquette_id');
    }
}
