<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260812122803 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Supprime le catalogue de cordages (type_cordage), redondant avec le stock de cordage réel : les licenciés choisissent désormais directement un article du stock disponible (demande_cordage.stock_cordage_id).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE demande_cordage DROP CONSTRAINT fk_8740957dab4dddff');
        $this->addSql('DROP INDEX idx_8740957dab4dddff');
        $this->addSql('ALTER TABLE demande_cordage DROP type_cordage_id');
        $this->addSql('DROP TABLE type_cordage');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE type_cordage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE demande_cordage ADD type_cordage_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_cordage ADD CONSTRAINT fk_8740957dab4dddff FOREIGN KEY (type_cordage_id) REFERENCES type_cordage (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_8740957dab4dddff ON demande_cordage (type_cordage_id)');
    }
}
